# Discord Faucet configuration
verbose = "yes"
core_team_role_id = 957288205391118337
network_denoms_url = "https://fetchnetworkdenomrequest-zbrmx4rjia-uc.a.run.app"

[envs]
    [envs.local]
    node_rpc = "http://localhost:36657"
    node_executable = "dymd"
    node_denom = "udym"
    node_chain_id = "dymension_100-1"
    network_name = "dymension"
    faucet_address = "dym1ctqdmjt7hntk2lxskgkphx73frt5h4f44ehjhx"
    address_prefix = "dym1"
    amount_to_send = "200000000"
    amount_to_send_evm = "200000000000000000000"
    daily_cap = "2000000000000"
    daily_cap_evm = "2000000000000000000000000"
    tx_fees = "50000"
    token_requests_cap = 6
    ibc_token_requests_cap = 6
    ibc_enabled = true
    channels_to_listen = ""
    request_timeout = "604800"
    client_type = "COSMOS"

    [envs.devnet]
    node_rpc = "https://rpc-dym-migration-test-2.mzonder.com:443"
    node_executable = "dymd"
    node_denom = "adym"
    node_chain_id = "dymension_1405-1"
    network_name = "Dymension Devnet"
    faucet_address = "dym1g8sf7w4cz5gtupa6y62h3q6a4gjv37pgefnpt5"
    address_prefix = "dym1"
    amount_to_send = "10000000"
    amount_to_send_evm = "10000000000000000000"
    daily_cap = "100000000000"
    daily_cap_evm = "100000000000000000000000"
    tx_fees = "1000000000000000"
    token_requests_cap = 6
    ibc_token_requests_cap = 6
    ibc_enabled = true
    channels_to_listen = "ðŸš°ãƒ»playground-faucet"
    request_timeout = "604800"
    client_type = "COSMOS"

    [envs.froopyland]
    node_rpc = "https://froopyland.blockpi.network:443/rpc/v1/0837569d56317f9a6af3c82170a7242ce8319ae4"
    node_executable = "dymd"
    node_denom = "udym"
    node_chain_id = "froopyland_100-1"
    network_name = "froopyland"
    faucet_address = "dym1g8sf7w4cz5gtupa6y62h3q6a4gjv37pgefnpt5"
    address_prefix = "dym1"
    amount_to_send = "200000000"
    amount_to_send_evm = "200000000000000000000"
    daily_cap = "2000000000000"
    daily_cap_evm = "2000000000000000000000000"
    tx_fees = "50000"
    block_explorer_tx="https://explorer.silknodes.io/dymension/tx/"
    token_requests_cap = 6
    ibc_token_requests_cap = 6
    ibc_enabled = true
    channels_to_listen = "ðŸš°ãƒ»froopyland-faucet"
    request_timeout = "604800"
    client_type = "COSMOS"

    [envs.blumbus]
    node_rpc = "https://dymension-testnet-tendermint.blastapi.io:443/291f79ab-77c1-4c90-b769-8218b1816f5c"
    node_executable = "dymd"
    node_denom = "adym"
    node_chain_id = "blumbus_111-1"
    network_name = "blumbus"
    faucet_address = "dym1g8sf7w4cz5gtupa6y62h3q6a4gjv37pgefnpt5"
    address_prefix = "dym1"
    amount_to_send = "10000000"
    amount_to_send_evm = "10000000000000000000"
    daily_cap = "100000000000"
    daily_cap_evm = "100000000000000000000000"
    tx_fees = "40000000000000000"
    block_explorer_tx="https://explorer.silknodes.io/blumbus/tx/"
    token_requests_cap = 6
    ibc_token_requests_cap = 6
    ibc_enabled = true
    channels_to_listen = "ðŸš°ãƒ»blumbus-faucet"
    request_timeout = "604800"
    client_type = "COSMOS"

    [envs.x]
    node_rpc = "https://rpc.rolxtwo.evm.ra.blumbus.noisnemyd.xyz:443"
    node_executable = "rollapp-evm"
    node_denom = "arolx"
    node_chain_id = "rolx_100004-1"
    network_name = "RollApp X"
    faucet_address = "rolx1g8sf7w4cz5gtupa6y62h3q6a4gjv37pg5aeahk"
    address_prefix = "rolx"
    amount_to_send = "20000000"
    amount_to_send_evm = "20000000000000000000"
    daily_cap = "200000000000"
    daily_cap_evm = "200000000000000000000000"
    tx_fees = "10000000000"
    block_explorer_tx=""
    token_requests_cap = 6
    ibc_token_requests_cap = 6
    ibc_enabled = true
    channels_to_listen = "ðŸš°ãƒ»rollapp-x-faucet"
    request_timeout = "604800"
    client_type = "COSMOS"

    [envs.y]
    node_rpc = "https://rpc.roly.wasm.ra.blumbus.noisnemyd.xyz:443"
    node_executable = "rollapp-evm"
    node_denom = "aroly"
    node_chain_id = "rollappy_700002-1"
    network_name = "RollApp Y"
    faucet_address = "roly1g8sf7w4cz5gtupa6y62h3q6a4gjv37pglrwk6a"
    address_prefix = "roly"
    amount_to_send = "200000000"
    amount_to_send_evm = "200000000000000000000"
    daily_cap = "2000000000000"
    daily_cap_evm = "2000000000000000000000000"
    tx_fees = "10000000000"
    block_explorer_tx=""
    token_requests_cap = 6
    ibc_token_requests_cap = 6
    ibc_enabled = true
    channels_to_listen = "ðŸš°ãƒ»rollapp-y-faucet"
    request_timeout = "604800"
    client_type = "COSMOS"

    [envs.celestia]
    node_rpc = "https://rpc.celestia-arabica-11.com:443"
    node_executable = "celestia-appd"
    node_denom = "utia"
    node_chain_id = "arabica-11"
    network_name = "arabica-11"
    faucet_address = "celestia1emd05tmxqy5z9mlccvudrmj8hnmds49t2le2r2"
    address_prefix = "celestia1"
    amount_to_send = "50000000"
    daily_cap = "50000000000"
    tx_fees = "21000"
    token_requests_cap = 6
    ibc_enabled = false
    channels_to_listen = "ðŸš°ãƒ»celestia-faucet"
    request_timeout = "604800"
    client_type = "COSMOS"

